swagger: '2.0'
info:
  description: >-
    API para gestão de um Sistema de Usuários de Carros
  version: 1.0.0
  title: CarUserSystem
  contact:
    email: dieggopsc@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: com.desafio.CarUserSystem
basePath: /
tags:
  - name: usuario
    description: Operações de Usuários
  - name: carro
    description: Operações de Carros
schemes:
  - http
paths:
  /api/signin:
    get:
      tags:
        - usuario
      summary: Visualização dos dados do usuario logado
      description: Esta rota espera um objeto com os campos login e password, e deve retornar o token de acesso da API (JWT) com as informações do usuário logado.
      operationId: logarUsuario
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/UsuarioLoginResponse'
        '404':
          description: Invalid login or password
definitions:
  Usuario:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      birthday:
        type: string
      login:
        type: string
      password:
        type: string
      phone:
        type: string
      cars:
        type: array
        items:
          $ref: '#/definitions/Cars'
  Cars:
    type: object
    properties:
      year:
        type: string
      licensePlate:
        type: string
      model:
        type: string
      color:
        type: string
  UsuarioLoginResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      birthday:
        type: string
      phone:
        type: string
      cars:
        type: array
        items:
          $ref: '#/definitions/Cars'
externalDocs:
  description: Swagger
  url: 'http://swagger.io'